services:
  web1:
    image: nginx:alpine
    networks:
      - net1
  web2:
    image: nginx:alpine
    networks: 
      - net2
  web3:
    image: nginx:alpine
    networks:
      - net1
      - net2
networks:
  net1:
  net2:
    external: true
